### ISSUE TITLE
Deprecate the old repos

### ISSUE THREAD

**Issue by johnpapa** [spboyer/advocate-linkers#10]
deprecate or redirect the olds repos.

**Comment by spboyer** [comment]
https://github.com/spboyer/social-linker : DEPRECATED message added

**Comment by johnpapa** [comment]
revision ... deprecate or say MOVED

**Comment by MaximRouiller** [comment]
Done. https://github.com/MaximRouiller/mobile-social-linker

We can close.

**Comment by spboyer** [comment]
Thanks all!
