### ISSUE TITLE
Fix the order of tactic/category

### ISSUE THREAD

**Issue by MaximRouiller** [spboyer/advocate-linkers#7]

**Comment by johnpapa** [comment]
What do you need done here?

`tactic-category-alias` is what we have today

**Comment by MaximRouiller** [comment]
The social linker should do things in this order: `tactic-social-myalias`

As `social` is the category and not `twitter`. When you pass the link through it, it creates `social-twitter-myalias` instead. This needs to be fixed.

**Comment by johnpapa** [comment]
Ok. So the links are wrong. Not the left right order of the inputs. 

I’ll fix this. Thanks.

**Comment by MaximRouiller** [comment]
Exactly. `twitter` is being used in the `category` property while it should be in the `tactic`. All others should also be tested.

Eventually, we should have tests to validate those as well.
